#ifndef OUTER_SHELL_API_H
#define OUTER_SHELL_API_H

#include "OuterShellBuffer.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define OUTERSHELL_API_MAX_FRAME_SIZE (16u * 1024u * 1024u)
#define OUTERSHELLD_API_FILE_OPENERS_ROW_SIZE 44u

enum {
    OUTERSHELLD_API_BACKEND_UPSERT_REQUEST = 10,
    OUTERSHELLD_API_BACKEND_REMOVE_REQUEST = 11,
    OUTERSHELLD_API_BACKEND_LIST_REQUEST = 12,
    OUTERSHELLD_API_APP_ADD_REQUEST = 13,
    OUTERSHELLD_API_APP_REMOVE_REQUEST = 14,
    OUTERSHELLD_API_APP_CLEAR_REQUEST = 15,
    OUTERSHELLD_API_APP_LIST_REQUEST = 16,
    OUTERSHELLD_API_LOG_ADD_REQUEST = 17,
    OUTERSHELLD_API_LOG_REMOVE_REQUEST = 18,
    OUTERSHELLD_API_LOG_CLEAR_REQUEST = 19,
    OUTERSHELLD_API_LOG_LIST_REQUEST = 20,
    OUTERSHELLD_API_SERVICE_MANAGER_CLEAR_REQUEST = 21,
    OUTERSHELLD_API_SERVICE_MANAGER_LIST_REQUEST = 22,
    OUTERSHELLD_API_CONTENT_TYPE_ADD_REQUEST = 23,
    OUTERSHELLD_API_CONTENT_TYPE_REMOVE_REQUEST = 24,
    OUTERSHELLD_API_CONTENT_TYPE_CLEAR_REQUEST = 25,
    OUTERSHELLD_API_CONTENT_TYPE_LIST_REQUEST = 26,
    OUTERSHELLD_API_OPENER_ADD_REQUEST = 27,
    OUTERSHELLD_API_OPENER_REMOVE_REQUEST = 28,
    OUTERSHELLD_API_OPENER_CLEAR_REQUEST = 29,
    OUTERSHELLD_API_OPENER_LIST_REQUEST = 30,
    OUTERSHELLD_API_FILE_OPENERS_QUERY = 31,
    OUTERSHELLD_API_UI_REQUEST = 32,
    OUTERSHELLD_API_COMMAND_RESPONSE = 100,
    OUTERSHELLD_API_BACKEND_LIST_RESPONSE = 101,
    OUTERSHELLD_API_APP_LIST_RESPONSE = 102,
    OUTERSHELLD_API_LOG_LIST_RESPONSE = 103,
    OUTERSHELLD_API_SERVICE_MANAGER_LIST_RESPONSE = 104,
    OUTERSHELLD_API_CONTENT_TYPE_LIST_RESPONSE = 105,
    OUTERSHELLD_API_OPENER_LIST_RESPONSE = 106,
    OUTERSHELLD_API_FILE_OPENERS_RESPONSE = 107,
    OUTERSHELLD_API_UI_RESPONSE = 108
};

enum {
    OUTERSHELLD_API_FLAG_OWNS_SERVICE_MANAGER_ENTRY = 0x01,
    OUTERSHELLD_API_FLAG_INCLUDE_ICONS = 0x02
};

enum {
    OUTERSHELLD_API_OPENER_CAPABILITY_VIEW = 0x01,
    OUTERSHELLD_API_OPENER_CAPABILITY_EDIT = 0x02,
    OUTERSHELLD_API_OPENER_CAPABILITY_DEFAULT =
        OUTERSHELLD_API_OPENER_CAPABILITY_VIEW | OUTERSHELLD_API_OPENER_CAPABILITY_EDIT
};

enum {
    OUTERSHELLD_UI_ROUTE_NONE = 0,
    OUTERSHELLD_UI_ROUTE_BACKENDS = 1,
    OUTERSHELLD_UI_ROUTE_LOGS = 2,
    OUTERSHELLD_UI_ROUTE_CONTROL = 3,
    OUTERSHELLD_UI_ROUTE_CREATE = 4,
    OUTERSHELLD_UI_ROUTE_RECIPES = 5,
    OUTERSHELLD_UI_ROUTE_FILE_PICKER = 6,
    OUTERSHELLD_UI_ROUTE_EVENTS = 7
};

typedef enum {
    UI_API_CONTENT_BINARY = 1,
    UI_API_CONTENT_TEXT = 2
} UiApiContentKind;

typedef struct {
    int status;
    UiApiContentKind content_kind;
    StringBuilder body;
} UiApiResponse;

bool api_read_string_ref(const unsigned char *message, size_t message_length, size_t ref_offset, char **out);
bool api_read_data_ref(const unsigned char *message, size_t message_length, size_t ref_offset, const unsigned char **out, size_t *out_length);
bool api_send_frame(int fd, StringBuilder *message);

#endif
