const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
const source=fs.readFileSync((process.argv[2]||process.cwd())+'/Resources/OuterShellWeb/app.js','utf8');
let html='',copied='';
const workspace={id:'w',name:'Projects',state:'running',shellCommand:'docker exec -it box sh',commands:[{id:'terminal',displayName:'Codex <CLI>',containerCommand:"docker exec -it box sh -lc 'cd /work && codex'",internalCommand:'cd /work && codex',iconURL:'/api/icon?key=123'}]};
const nodes=[0,1,2].map(index=>({dataset:{copyVariant:String(index)},events:{},addEventListener(name,fn){this.events[name]=fn;}}));
const context={window:{},safeSpaceIsRunning:w=>w.state==='running',containerPreparing:()=>false,escapeHTML:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),findSafeSpace:()=>workspace,contextMenuGlyph:()=>'',closeDialog(){},showContextMenu:s=>{html=s;return {querySelectorAll:()=>nodes};},copyText:s=>copied=s};
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('  function containerCommands('),source.indexOf('  function renderOverview(')),context);
assert.equal(context.containerCommands(workspace).length,2);
assert.match(context.containerCommandsHTML(workspace),/Codex &lt;CLI>/);
assert.equal(context.containerCommandsHTML(null),'');
const command=context.containerCommands(workspace)[1];
assert.equal(context.containerCommandVariants(command).length,2);
context.window.outerLoop={sessionContext:{sshCommandArguments:['ssh','-i',"/key path/it's a key",'-p','2222','user@server']}};
const variants=context.containerCommandVariants(command);
assert.equal(variants.length,3);
const parsed=JSON.parse(execFileSync('python3',['-c','import shlex,json,sys; print(json.dumps(shlex.split(sys.argv[1])))',variants[0].text],{encoding:'utf8'}));
assert.deepEqual(parsed,['ssh','-t','-i',"/key path/it's a key",'-p','2222','user@server',command.text]);
assert.equal(context.containerCommandVariants(context.containerCommands(workspace)[0]).length,2);
context.openContainerCommand('w','command:terminal');
assert(!html.includes(command.text));assert(!html.includes(command.internalText));
assert.match(html,/Copy SSH command/);assert.match(html,/Copy container command/);assert.match(html,/Copy internal command/);
nodes[0].events.click();assert.equal(copied,variants[0].text);
nodes[1].events.click();assert.equal(copied,command.text);
nodes[2].events.click();assert.equal(copied,command.internalText);
assert.match(context.containerCommandsHTML(workspace),/<svg viewBox/);
workspace.state='stopped';assert.match(context.containerCommandsHTML(workspace),/disabled/);html='';context.openContainerCommand('w','terminal');assert.equal(html,'');
console.log('PASS: all copy variants, SSH quoting and PTY, no-SSH fallback, copy menu without raw commands, stopped-container gating');
